# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# compile CXX with /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
CXX_FLAGS =  -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security  -Wmissing-prototypes -Wstrict-prototypes  -Winit-self -Wpointer-arith  -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wno-array-bounds -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -msse3 -Wno-shadow -Wno-unused -Wno-sign-compare -Wno-undef -Wno-missing-declarations -Wno-uninitialized -Wno-switch -Wno-parentheses -Wno-array-bounds -Wno-extra -Wno-deprecated-declarations -fPIC -O3 -DNDEBUG  -DNDEBUG  

CXX_DEFINES = 

CXX_INCLUDES = -I/Users/liuzhaoliang/AllAboutLZL/Lib/OpenCV2.4.13/opencv-2.4.13.3-source/3rdparty/openexr/IlmImf -I/Users/liuzhaoliang/AllAboutLZL/Lib/OpenCV2.4.13/opencv-2.4.13.3-source/3rdparty/openexr/Imath -I/Users/liuzhaoliang/AllAboutLZL/Lib/OpenCV2.4.13/opencv-2.4.13.3-source/3rdparty/openexr/IlmThread -I/Users/liuzhaoliang/AllAboutLZL/Lib/OpenCV2.4.13/opencv-2.4.13.3-source/3rdparty/openexr/Iex -I/Users/liuzhaoliang/AllAboutLZL/Lib/OpenCV2.4.13/opencv-2.4.13.3-source/3rdparty/openexr/Half -I/Users/liuzhaoliang/AllAboutLZL/Lib/OpenCV2.4.13/opencv-2.4.13.3-source/build-static/3rdparty/zlib -I/Users/liuzhaoliang/AllAboutLZL/Lib/OpenCV2.4.13/opencv-2.4.13.3-source/3rdparty/zlib -I/Users/liuzhaoliang/AllAboutLZL/Lib/OpenCV2.4.13/opencv-2.4.13.3-source/build-static/3rdparty/openexr -I/Users/liuzhaoliang/AllAboutLZL/Lib/OpenCV2.4.13/opencv-2.4.13.3-source/build-static 

